spring:
  application:
    name: check-book-service
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        input:
          destination: create-book
        output:
          destination: store-book
          contentType: application/json

server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
Lospring:
  sleuth:
    sampler:
      probability: 2.0