spring:
  application:
    name: creation-book-service
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true

      bindings:
        output:
          destination: create-book


server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
Lospring:
  sleuth:
    sampler:
      probability: 2.0